In [1]:
import numpy as np

In [2]:
# Create an array of 10 zeros
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
# Create an array of 10 ones
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
# Create an array of 10 fives
np.array([5] * 10)

# np.ones(10) + 5
# np.ones(10) * 5

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [6]:
# Create an array of integers from 10 to 50
np.arange(10, 51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [8]:
# Create an array of all the even numbers from 10 to 50
np.arange(10, 51, 2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [9]:
# Create a 3x3 matrix with values from 0 to 8
arr = np.arange(0, 9)
arr.reshape(3, 3)

# np.arange(0, 9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
# Use NumPy to generate a random number from 0 to 1
np.random.rand()

0.07978901930311755

In [12]:
# Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution
np.random.randn(25)

array([ 1.34141028,  0.52582242,  0.67311293, -0.78097283,  0.61463015,
        1.31783687,  0.71699251, -0.00814919,  1.03052393, -0.2085268 ,
       -1.15238033, -0.10111039, -0.48804884, -1.2270829 ,  1.02846306,
        1.39899717,  1.58896494, -0.28470058,  0.85993495,  1.25533525,
       -0.01684429, -0.17769954,  1.15296658,  0.64412478, -0.40837964])

In [13]:
# Create an array of 20 linearly spaced points between 0 and 1
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [14]:
# Using the matrix below from now on
arr = np.arange(1, 26).reshape(5, 5)

In [15]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [17]:
# Select the last 4 elements from the last 3 rows
arr[2:, 1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [20]:
# Select the value 20 from the array
arr[3, 4]

# arr[arr == 20]

20

In [23]:
# Select the values 2, 7, 12 from the array as an array
arr[:3, 1].reshape(3,1)

# arr[:3, 1:2]

array([[ 2],
       [ 7],
       [12]])

In [26]:
# Select the last row of the array
arr[-1]

# Select the row located at index 4 from the array
# arr[4]

array([21, 22, 23, 24, 25])

In [28]:
# Get the sum of all the values from the array
arr.sum()

# np.sum(arr)

325

In [30]:
# Get the standard deviation of the values inside the array
arr.std()

7.211102550927978

In [31]:
# Get the sum of all the columns inside the array
arr.sum(axis=0)

array([55, 60, 65, 70, 75])

In [32]:
# Get the same random numbers in NumPy
np.random.seed(42)
np.random.rand(10)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864,
       0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258])

In [33]:
# Get the same random numbers in NumPy
np.random.seed(42)
np.random.rand(10)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864,
       0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258])