Prima librărie pe care o să o învățăm este 'numpy'. Aproape toate librăriile pe care le vom folosi în cadrul acestui tutorial sunt bazate pe 'numpy'. Scopul aceste secțiuni este să învățăm următoarele lucrui:

-  Să înțelegem librăria numpy

-  Să creem listte (arrays) utilizând numpy

-  Să preluăm informații dintr-un array de numpy utilizând partea de slicing și de indexare

-  Să învățăm operații basic de numpy

### Ce anume este NumPy?

NumPy este o librărie din Python utilizată pentru a crea N dimensional Arrays (liste de o dimensiune N). N dimensional Array înseamnă că aceste array-uri pot fi structurate ușor de la 1D la 2D, la 3D, la 4D etc. Ce este important pentru NumPy, este abilitatea de a difuza rapid funcții și are o mulțime de funcționalități deja create, precum algebră lineară, distribuție spațială, funcții trigonometrice.

Deși la primva vedere un array din NumPy este foarte asemănător cu o listă din Python, defapt aceste arrays sunt mult mai mult de atâta. Procedeul de a difuaz funcții pe permite să aplicăm o funcție pe un întreg data set foarte ușor și rapid.

# NumPy Arrays

Există mai multe metode prin care putem crea un array în NumPy, dar o să ne focusăm doar pe trei

-   transformarea unei liste din Python într-un array

-  utilizarea unor funcții buit-in

-  generarea de date random utilizând NumPy

 Pentru a putea utiliza librăria, aceasta trebui instalată și după importată. Pentru a instala librăria o să ne folosim de comanda pip

Prin convenție, importăm librărial NumPy sub denumirea de 'np'

In [2]:
import numpy as np

După ce am importat librăria NumPy să învățăm cum anume putem crea un array. Putem să creem un aray prim transformarea unei liste normale din Python

In [3]:
mylist = [1, 2, 3]

In [4]:
type(mylist)

list

Pentru a transforma o listă într-un array, o să utilizăm metoda `array()`. În cadrul acestei metode o să trecem lista respectivă

In [5]:
np.array(mylist)

array([1, 2, 3])

Din output-ul de mai sus se poate observa faptul că acel obiect este acuma un array. Putem să salvăm codul de mai sus în cadrul unei variabiel și după să vedem ce tip de obiect este

In [6]:
myarr = np.array(mylist)

In [7]:
type(myarr)

numpy.ndarray

Putem să trecem și la nivelul următor, acela de a crea un vector bi dimensional (precum o matrice)

In [8]:
mymatrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
mymatrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

În acest moment, ceea se afișează este o listă care este formată din trei liste individuale. Putem să pasăm această listă ca și argument pentru metoda 'array()' ca să vedem ce anume se întâmplă.

In [10]:
np.array(mymatrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Se poate observa că numpy are fundamentele stabilite și recunoaște faptul că lista respectivă este una bi-dimensională

De cele mai multe ori nu o să avem foarte mult de a face cu partea de convertire de date într-un array din numpy, ci cel mai mult o să ne folosim de metodele existente în cadrul acestei librării. Să aruncăm o privire peste aceste librării.

### np.arange()

Metoda respectivă este echivalentul din Python pentru 'range()'. Ca și argumente trebuie să îi oferim un punct de plecare, unul de sosire și opțional un step. Metoda o să retunreze un array cu valorile respective

In [11]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [13]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

### np.zeros()

Un caz foarte comun este acela de a crea un array foarte mare de date ce conțin valorile 0 și 1. Metoda ce va fi utilizată pentru acest scop este 'np.zeros()
'

In [14]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

Comanda de mai sus creează un array one dimensional cu 5 valori de zero în cadrul acelui array. De reținut este faptul că această metodă creează valorile respective ca și valori de tipul float pentru a păstra o precizie mai bună. Dacă dorim să creem un array bi-dimensional, atunci ca și argument putem să trecem un tuple, unde prima valoare reprezintă numărul de râduri, iar a doua reprezintă numărul de coloane.

In [15]:
np.zeros((5, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])