Prima librărie pe care o să o învățăm este 'numpy'. Aproape toate librăriile pe care le vom folosi în cadrul acestui tutorial sunt bazate pe 'numpy'. Scopul aceste secțiuni este să învățăm următoarele lucrui:

-  Să înțelegem librăria numpy

-  Să creem listte (arrays) utilizând numpy

-  Să preluăm informații dintr-un array de numpy utilizând partea de slicing și de indexare

-  Să învățăm operații basic de numpy

### Ce anume este NumPy?

NumPy este o librărie din Python utilizată pentru a crea N dimensional Arrays (liste de o dimensiune N). N dimensional Array înseamnă că aceste array-uri pot fi structurate ușor de la 1D la 2D, la 3D, la 4D etc. Ce este important pentru NumPy, este abilitatea de a difuza rapid funcții și are o mulțime de funcționalități deja create, precum algebră lineară, distribuție spațială, funcții trigonometrice.

Deși la primva vedere un array din NumPy este foarte asemănător cu o listă din Python, defapt aceste arrays sunt mult mai mult de atâta. Procedeul de a difuaz funcții pe permite să aplicăm o funcție pe un întreg data set foarte ușor și rapid.

# NumPy Arrays

Există mai multe metode prin care putem crea un array în NumPy, dar o să ne focusăm doar pe trei

-   transformarea unei liste din Python într-un array

-  utilizarea unor funcții buit-in

-  generarea de date random utilizând NumPy

 Pentru a putea utiliza librăria, aceasta trebui instalată și după importată. Pentru a instala librăria o să ne folosim de comanda pip

Prin convenție, importăm librărial NumPy sub denumirea de 'np'

In [2]:
import numpy as np

După ce am importat librăria NumPy să învățăm cum anume putem crea un array. Putem să creem un aray prim transformarea unei liste normale din Python

In [3]:
mylist = [1, 2, 3]

In [4]:
type(mylist)

list

Pentru a transforma o listă într-un array, o să utilizăm metoda `array()`. În cadrul acestei metode o să trecem lista respectivă

In [5]:
np.array(mylist)

array([1, 2, 3])

Din output-ul de mai sus se poate observa faptul că acel obiect este acuma un array. Putem să salvăm codul de mai sus în cadrul unei variabiel și după să vedem ce tip de obiect este

In [6]:
myarr = np.array(mylist)

In [7]:
type(myarr)

numpy.ndarray

Putem să trecem și la nivelul următor, acela de a crea un vector bi dimensional (precum o matrice)

In [8]:
mymatrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
mymatrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

În acest moment, ceea se afișează este o listă care este formată din trei liste individuale. Putem să pasăm această listă ca și argument pentru metoda 'array()' ca să vedem ce anume se întâmplă.

In [10]:
np.array(mymatrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Se poate observa că numpy are fundamentele stabilite și recunoaște faptul că lista respectivă este una bi-dimensională

De cele mai multe ori nu o să avem foarte mult de a face cu partea de convertire de date într-un array din numpy, ci cel mai mult o să ne folosim de metodele existente în cadrul acestei librării. Să aruncăm o privire peste aceste librării.

### np.arange()

Metoda respectivă este echivalentul din Python pentru 'range()'. Ca și argumente trebuie să îi oferim un punct de plecare, unul de sosire și opțional un step. Metoda o să retunreze un array cu valorile respective

In [11]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [13]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

### np.zeros()

Un caz foarte comun este acela de a crea un array foarte mare de date ce conțin valorile 0 și 1. Metoda ce va fi utilizată pentru acest scop este 'np.zeros()
'

In [14]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

Comanda de mai sus creează un array one dimensional cu 5 valori de zero în cadrul acelui array. De reținut este faptul că această metodă creează valorile respective ca și valori de tipul float pentru a păstra o precizie mai bună. Dacă dorim să creem un array bi-dimensional, atunci ca și argument putem să trecem un tuple, unde prima valoare reprezintă numărul de râduri, iar a doua reprezintă numărul de coloane.

In [15]:
np.zeros((5, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### np.ones()

Metoda 'np.ones()' este extrem de similară precum 'np.zeros()', realizează același lucru, doar că în loc de valoarea 0. o să ne creeze un array cu valoarea 1.

In [16]:
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

### np.linspace()

O altă metodă des utilizată o să fie cea de 'np.linespace()'. Această funcție returnează o serie de numere separate egal între ele în funcție de un interval specificat. Să nu se confunde cu sintaxa de la 'np.arange()' deoarece aceasta este un pic diferită. Funcția aceasta ia un argument pentru limita de start și altul pentru limita de final. Până aici este foarte asemănătoare cu metoda 'np.arange()'. Diferența vine pentru argumentul al treilea, argumentul care reprezintă numărul de elemente ce dorim să fie prezent în cadrul array-ului. Acel număr de elemente o să fie numai valori cuprinse între valorile setate pentru partea de start și stop.

In [17]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

Până în acest moment am trecut peste câteva funcții prin care putem crea un array după o listă din Python, sau altele prin care putem crea un array după un range în funcție de o valorea de start, una de stop, iar uneori un step. Ne-am mai uitat și peste partea prin care putem să creem un array (uni dimensional sau bi dimensional) doar cu valori de 0 sau 1. În continuare o să ne uităm peste modalitatea de a crea array cu anumite date random. Există multe librării pe care le-am putea utiliza pentru a crea date random. Din fericire, NumPy vine cu propria parte de generare de date random care poartă denumirea de 'random'

Din cadrul acestei librării putem crea un array de date random (date cuprinse între valorile 0 și 1) utilizând metoda 'rand()'. Acestei metode trebuie să îi oferim ca și argument fie un singur număr (caz în care creează un array uni dimensional), fie două numere, caz în care creează un array bi dimensional.

### np.random.rand()

In [3]:
np.random.rand(5)

array([0.03070382, 0.79819811, 0.1494731 , 0.6051938 , 0.97335252])

In [4]:
np.random.rand(5, 2)

array([[0.73594585, 0.37002815],
       [0.70861372, 0.739056  ],
       [0.20977399, 0.21886293],
       [0.68482048, 0.12951716],
       [0.13466566, 0.30613287]])

### np.random.randint()

O altă metodă ce poate fi utilizată este moetoda 'randint()'. Metoda aceasta retunrează nu număr întreg între 2 valori specificate ca și argument

In [6]:
np.random.randint(0, 10)

8

Pentru codul de mai sus, metoda returnează un număr random între valorile 0 și 10. Dacă dorim să ne returneze un array de valori uni dimensional, atunci trebuie să specificăm numărul de valori din array care să fie returnat

In [7]:
np.random.randint(0, 50, 3)

array([18,  3, 38])

În situația în care se dorește să se retunreze un array bi dimensional de valori alese la întânplare utilizând metoda 'randint()', atunci pentru argumentul de valori o să se treacă un tuple.Î

In [8]:
np.random.randint(0, 50, (5, 2))

array([[35,  0],
       [33, 30],
       [ 0, 39],
       [40, 24],
       [48, 16]])

### np.random.seed()

Pentru a putea lucra cu astfel de date, cu date generate random (pseudo-random generated numbers) uneori este nevoie să utilizăm poate același set de date pentru a putea face debugging la o anumită parte de cod. În această situație intră în calcul metode 'seed()', metodă prin care putem să setăm 'rădăcina' (adică inputul) pentru algoritmul de generare de date random (deoarece aceste date se generează pe bază de algoritm). Din moment ce am setat acel 'seed', atunci putem să obținem același set de date cu valori așa zise 'random'.

Pentru mai multe informații despre 'pseudo-random numbers' se poate accesa link-ul https://www.sharpsightlabs.com/blog/numpy-random-seed/

In [10]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

Dacă se rulează același cod din nou, se va observa că o să avem același rezultat

In [11]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

Un lucru de ținut minte este faptul că acele rânduri de cod trebuie trecute în aceași celulă pentru a primi aceleași rezultate. De asemenea, numărul '42' reprezintă așa zisa 'rădăcină' de la care pornește algoritmul de generare de numere, prin urmare acel număr poate fi modificat după placul utilizatorului, dar de reținut că atunci când se modidifică acea valore, atunci o să se modifice și valoarile returnate ca fiind 'random'

Această metodă o să o utilizăm destul de des în cadrul acestui curs.

În continuare o să trecem peste anumite atribute și metode utilie pentru un array din NumPy. Pentru a le putea utiliza, trebui întâi să creem acest array.

In [12]:
arr = np.arange(0, 25)

In [13]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

### .reshape()

Ce anumte putem să facem cu acest array este să îl remodelăm. Prin remodelare putem să ne imaginăm la tipul array-ului (din uni dimensional să îl transformăm în bi-dimensional) sau dacă e cazul unui array bi-dimensional să îi modificăm structura. Din 5 coloane și 2 rânduri să modificăm astfel ca acest array să fie de 2 rânduri și 5 coloane. Metoda prin care putem face această operațiune poartă denumirea de 'reshape()'.

In [14]:
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

În array-ul de mai sus sunt prezente 25 de elemente. Dacă dorim să facem reshape la o un array care la final nu are 25 de elemente, atunci o să rezulte o eroare

In [16]:
arr.reshape(5, 4)

ValueError: cannot reshape array of size 25 into shape (5,4)

### .max() 

### .min()

### .argmax()

### .argmin()

Metodele de mai sunt iar anumite metode utilizate mai des cu NumPy. Metodele '.max()' și '.min()' returnează valoarea cea mai mare, repsectiv cea mai mică din cadrul unui array, iar aceleași metode, dar cu 'arg' ca și sufix ('argmax()' și 'argmin()') returnează index-ul pe care se găsesc acele valori (valoarea maximă sau valoarea minimă)

In [17]:
# creating an array of random numbers

rand_arr = np.random.randint(0, 100, 20)

In [19]:
# printing the values inside the array
rand_arr

array([82, 86, 74, 74, 87, 99, 23,  2, 21, 52,  1, 87, 29, 37,  1, 63, 59,
       20, 32, 75])

In [26]:
# printing the highest values from the array
rand_arr.max()

99

In [24]:
# printing the index of the highest value from the array
rand_arr.argmax()

5

In [27]:
# printing the smallest values from the array
rand_arr.min()

1

In [28]:
# printing the index of the smallest value from the array
rand_arr.argmin()

10

### .dtype

Putem să aflăm tipul de date ce este prezent în cadrul unui array utilizând atributul '.dtype'

In [30]:
rand_arr.dtype

dtype('int64')

## Recapitulare

În această parte din curs am învățat următoarele lucruri:

    1. Cum să creem un array după o listă de valori

        mylist = [1, 2, 3]

        np.array(mylist)

    2. Cum să creem un array dintr-un range de valori 

        np.arange(0, 10) # fără argumentul de step

        np.arange(0, 10, 2) # cu argumentul de step

    3. Cum să creem un array doar cu valori de 0

        np.zeros(4) # un array uni dimensional

        np.zeros((4, 2)) # un array bi-dimenional unde 4 reprezintă numărul de rânduri, iar 2 numărul de coloane. Aceste valori trebuie menționate în cadrul unui tuple

    4. Cum să creem un array doar cu valori de 1

        np.ones(4) # un array uni dimensional

        np.ones((4, 2)) # un array bi-dimenional unde 4 reprezintă numărul de rânduri, iar 2 numărul de coloane. Aceste valori trebuie menționate în cadrul unui tuple

    5. Cum să creem un array cu valori ce conțin distanța egală între acestea

        np.linspace(0, 10, 3) # retunrează un array de 3 valori cu distanță egală între ele între valorile 0 și 10 (ambele valori incluse). Prin urmare o să returneze array([ 0.,  5., 10.])

    6. Cum să creem un array cu valori așa zise random

        np.random.rand(4) # returnează un array uni-dimensional de 4 elemente cu valori random cuprinse între 0 și 1

        np.random.rand(4, 2) # returnează un array bi-dimensional de 4 rânduri și 2 coloane cu valori random cuprinse între 0 și 1

    7. Cum să creem un array de valori întregi așa zise random

        np.random.randint(0, 10) # returează un număr întreg random între valorile 0 și 10

        np.random.randint(0, 10, 4) # retunrează un array uni-dimensional de 4 elemente cu valori random între 0 și 10

        np.random.randint(0, 10, (4, 2)) # returnează un array bi-dimensional de 4 rânduri și 2 coloane cu valori random între 0 și 10

    8. Cum să shimbăm 'rădăcina' pentru algoritmul de generare de numere random

        np.random.seed(42) # utilizăm ca și 'rădăcină' pentru algoritmul de calcul valorea 42. Se va utiliza împreună cu o metodă de generare de valori random

        np.random.rand(4) # în combinație cu np.random.seed(42) o să returneze mereu aceleași valori

    9. Cum să remodelăm un array

        arr = np.arange(0, 25)

        arr.reshape(5, 5)

    10. Utilizarea unor metode și atribute utile 

        arr.max()

        arr.argmax()

        arr.min()

        arr.argmin()

        arr.dtype

        

